### ISSUE TITLE
android 12适配

### ISSUE THREAD

**Issue by GXSZone** [kongqw/QQHelper#1]
android 12要加
 android:exported="true"

  现在有maven了 api 'com.tencent.tauth:qqopensdk:3.52.0'

**Comment by kongqw** [comment]
感谢反馈，近期就更新！

**Comment by kongqw** [comment]
1.3.1 更新了。

'com.tencent.tauth:qqopensdk:3.52.0' 发布在jcenter，google已经不再建议使用了，另外这个库是21年的版本，还不支持隐私合规等问题，不要考虑使用这个版本了。
